# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1alNCSmOvaRIxEdgM0dVgVuEJKeqJ2bw5
"""

import pandas as pd

data = pd.read_excel("Dataset.xlsx")

#data

#data.head(5)

#data['Label ']

new_label = data['Label '].tolist()
#new_label

#n = data[data['Label ']=='Female']

#n

new_unnamed = data['Unnamed: 3'].tolist()

#new_unnamed

with open('Hierarchy.txt', 'r') as f:
  labels = f.readlines()

labels = [x.strip() for x in labels]
#labels

labels_dict = dict((labels[i],i+1) for i in range(len(labels)))
#labels_dict

#not_present = list()
for i in range(len(new_label)):
  if new_unnamed[i]=='Ranking':
    new_label[i] = labels_dict['Rating attribute']
    continue
  if new_label[i] in labels_dict:
    new_label[i] = labels_dict[new_label[i]]
  elif new_label[i] == 'Female':
    new_label[i] = labels_dict['Human']
  elif new_label[i] == 'Recording':
    new_label[i] = labels_dict['Other']
  else:
    new_label[i] = labels_dict['Rating attribute']

#new_label

new_dict = {'Label' : new_label}

#new_dict

new_df = pd.DataFrame(data = new_dict)

#new_df

new_df.to_csv("new_label.csv")

